# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

#######default_platform(:ios)

#######platform :ios do
#######  desc "Upload build to TestFlight"
#######  lane :beta do
#######    increment_build_number
#######    get_certificates    
#######    get_provisioning_profile
#######    build_app
#######    upload_to_testflight
#######  end
#######end

default_platform :ios

platform :ios do
  ####### Testing #######

    desc "Runs all the tests"
    lane :tests do
      unit_tests
    end

    desc "Runs all unit tests"
    lane :unit_tests do
      scan(
        workspace: "Contributor.xcworkspace",
        scheme: "Contributor Staging 2",
        devices: ["iPhone 11"]
      )
    end

    #######desc "Runs all ui tests"
    #######lane :ui_tests do
      #######scan(
        #######workspace: "MyAmazingApp.xcworkspace",
        #######scheme: "MyAmazingAppTests",
        #######devices: ["iPhone 8"],
        #######clean: true
      #######)
    #######end

end
