name: "Testcases Run"

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build_test:
    name: Run tests
    runs-on: macOS-latest
    env:
        XCODE_VERSION: "14.0"

    steps:
      - name: Select XCode
        run: sudo xcode-select --switch /Applications/Xcode_${{ env.XCODE_VERSION }}.app

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run tests
        run: |
          set -o pipefail
          fastlane tests
